version: "3"

networks:
  wordpress:

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - "${DC_NGINX_PORT:-80}:80"
      - "${DC_NGINX_SSL_PORT:-443}:443"
    volumes:
      - "./wordpress:/var/www/html:delegated"
    depends_on:
      - php
      - mariadb
    networks:
      - wordpress
  mariadb:
    image: "mariadb:11.4"
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "${DC_MARIADB_DB_PORT:-3306}:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "${DC_MARIADB_DB_ROOTPASS}"
      MARIADB_DATABASE: "${DC_MARIADB_DB_NAME}"
      MARIADB_USER: "${DC_MARIADB_DB_USER}"
      MARIADB_PASSWORD: "${DC_MARIADB_DB_PASS}"
      TZ: "${DC_TZ}"
    volumes:
      - "./mariadb/config/my-cnf-overrides.cnf:/etc/mysql/conf.d/overrides.cnf"
      - "./mariadb/data:/var/lib/mysql"
      - "./mariadb/logs:/var/log/mysql"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 1m
      timeout: 5s
      retries: 3
    networks:
      - wordpress
  phpmyadmin:
    image: "phpmyadmin:5.2"
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      UPLOAD_LIMIT: 512M
    ports:
      - "${DC_PHPMYADMIN_HTTP_PORT:-8085}:80"
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - wordpress
  redis:
    image: "redis:7.4.0"
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - "./redis/data:/data"
      - "./redis/conf/redis.conf:/etc/redis/redis.conf"
    ports:
      - "${DC_REDIS_PORT:-6379}:6379"
    networks:
      - wordpress
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_php
    volumes:
      - "./wordpress:/var/www/html:delegated"
    networks:
      - wordpress
  wp:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_wp
    depends_on:
      - php
      - mariadb
    volumes:
      - "./wordpress:/var/www/html:delegated"
    entrypoint: ["wp", "--allow-root"]
    networks:
      - wordpress
